---
# tasks file for docker

- name: Remove docker if installed from CentOS repo
  yum:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest

- name: Convert old images to new runtime
  shell:
    cmd: "grep -rl 'docker-runc' /var/lib/docker/containers/ | xargs sed -i 's/docker-runc/runc/g' "
  changed_when: false
  failed_when: false

- name : "Create Groups"
  group:
    name: "docker"
    state: "present" 

- ansible.builtin.user:
    name: centos
    shell: /bin/bash
    groups: docker
    append: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

# - name: Start Docker service
#   shell:  |
#     sudo usermod -aG docker $USER
#     newgrp docker 

- name: Get version number of latest docker-compose
  shell:
    cmd: curl --silent 'https://api.github.com/repos/docker/compose/releases/latest' |  grep '"tag_name":' | sed 's/[^0-9.]*//g'
  register: docker_compose_latest_svn
  changed_when: false
  args:
    warn: no
-  debug: msg="Latest docker-compose version - {{ docker_compose_latest_svn }}"

- set_fact:
    docker_compose_latest: "{{ docker_compose_latest_svn.stdout }}"
  when:
    - docker_compose_latest_svn.stdout is defined

- name: Check if /usr/bin/docker-compose exists.
  stat:
    path: /usr/bin/docker-compose
  register: docker_compose_file

- name: Check current docker-compose version
  shell:
    cmd: /usr/bin/docker-compose --version | cut -d ' ' -f4 | sed 's/[^0-9.]*//g'
  register: docker_compose_vsn
  changed_when: false
  failed_when: false
  args:
    warn: no
  when:
    - docker_compose_file.stat.exists

- name: test | Check latest docker-compose version
  debug: msg="{{ docker_compose_latest_svn }}"

- name: test | Check current docker-compose version
  debug: msg="{{ docker_compose_vsn.stdout }}"
  when:
    - docker_compose_vsn.stdout is defined and docker_compose_file.stat.exists

- set_fact:
    docker_compose_current_version: "{{ docker_compose_vsn.stdout }}"
  when:
    - docker_compose_vsn.stdout is defined and docker_compose_file.stat.exists

- name: Install or upgrade docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_latest }}/docker-compose-Linux-x86_64"
    dest: /usr/bin/docker-compose
    mode: "a+x"
    force: yes
  when: >
    docker_compose_current_version is not defined
    or docker_compose_current_version is version(docker_compose_latest, '<')

- name: Remove docker-compose file
  file:
    path: "/usr/local/bin/docker-compose"
    state: absent

# - name: Reload shell
#   shell: source ~/.bashrc

- name: ensure required pip-packages are installed
  #become: true
  pip:
    name:
      - docker>=1.8.0
      - PyYAML>=3.11
      - docker-compose>=1.7.0
    executable: pip3
